version: '2'

services:

  demo-mysql:
    image: mysql:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=openvidu_sample_app
      - MYSQL_USER=op-root
      - MYSQL_PASSWORD=pass

  service-classroom-demo:
    image: openvidu/classroom-demo
    links:
      - demo-mysql:mysql
    ports:
      - 4443:4443
      - 5000:5000
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=120
      - KMS_STUN_IP=stun.l.google.com
      - KMS_STUN_PORT=19302
      - openvidu.secret=MY_SECRET
      - openvidu.publicurl=${OPENVIDU_PUBLICURL}
